### ISSUE TITLE
Inspect possibly weird type param mappings

### ISSUE THREAD

**Issue by KacperFKorban** [VirtusLab/Inkuire#33]
```
class C<in A>(xd: Int) {
  fun A.f<G>() {
    ???
  }
}

**Comment by pikinier20** [comment]
We need to deal with situations where extension methods are defined in some scope e.g. class and notify user that usage of this method can be tricky(it's available only with certain scope).

**Comment by BarkingBad** [comment]
It's not that bad. The scope you can get via `with` scope function
```kotlin
with(C<A>(1)) {
    someA_Instance.f()
}
```

**Comment by BarkingBad** [comment]
I'd extend model for `context` which holds the DRI of nesting class

**Comment by pikinier20** [comment]
For now, location column handles the problem
