### ISSUE TITLE
Mapping java primitives to proper types

### ISSUE THREAD

**Issue by KacperFKorban** [VirtusLab/Inkuire#52]
It's impossible to use primitives in `FluffMatchService` now, because DRI is needed to properly identify them.

Full list of signatures and types in them without DRIs:
typeOf: ReflectionFactoryImpl.(KClassifier, List<KTypeProjection>, boolean) -> KType    boolean
typeParameter: ReflectionFactoryImpl.(Object, String, KVariance, boolean) -> KTypeParameter    Object, boolean
setUpperBounds: ReflectionFactoryImpl.(KTypeParameter, List<KType>) -> void    void
clearCaches: ReflectionFactoryImpl.() -> void    void
getValue: ReflectProperties.Val.(Object, Object) -> T    Object, Object
getEnumConstantByName: Util.(Class<Enum<Object>>, String) -> Object    Object
containsKey: IntTree.(long) -> boolean    long, boolean
get: IntTree.(long) -> V    long
plus: IntTree.(long, V) -> IntTree<V>    long
minus: IntTree.(long) -> IntTree<V>    long
changeKeysAbove: IntTree.(long, int) -> IntTree<V>    long, int
changeKeysBelow: IntTree.(long, int) -> IntTree<V>    long, int
get: IntTreePMap.(int) -> V    int
plus: IntTreePMap.(int, V) -> IntTreePMap<V>    int
minus: IntTreePMap.(int) -> IntTreePMap<V>    int
size: HashPMap.() -> int    int
containsKey: HashPMap.(Object) -> boolean    Object, boolean
get: HashPMap.(Object) -> V    Object
minus: HashPMap.(Object) -> HashPMap<K, V>    Object
equals: MapEntry.(Object) -> boolean    Object, boolean
hashCode: MapEntry.() -> int    int
get: ConsPStack.(int) -> E    int
size: ConsPStack.() -> int    int
minus: ConsPStack.(int) -> ConsPStack<E>    int
forEach: Iterable.(Consumer<Object>) -> void    void
isInline: FunctionReference.() -> boolean    boolean
isExternal: FunctionReference.() -> boolean    boolean
isOperator: FunctionReference.() -> boolean    boolean
isInfix: FunctionReference.() -> boolean    boolean
isSuspend: FunctionReference.() -> boolean    boolean
equals: FunctionReference.(Object) -> boolean    Object, boolean
hashCode: FunctionReference.() -> int    int
getBoundReceiver: CallableReference.() -> Object    Object
call: CallableReference.(Array<Object>) -> Object    Object
callBy: CallableReference.(Map) -> Object    Object
isFinal: CallableReference.() -> boolean    boolean
isOpen: CallableReference.() -> boolean    boolean
isAbstract: CallableReference.() -> boolean    boolean
isFinal: KCallable.() -> boolean    boolean
isOpen: KCallable.() -> boolean    boolean
isAbstract: KCallable.() -> boolean    boolean
isSuspend: KCallable.() -> boolean    boolean
getArity: FunctionBase.() -> int    int
isInline: KFunction.() -> boolean    boolean
isExternal: KFunction.() -> boolean    boolean
isOperator: KFunction.() -> boolean    boolean
isInfix: KFunction.() -> boolean    boolean
get: MutablePropertyReference0Impl.() -> Object    Object
set: MutablePropertyReference0Impl.(Object) -> void    Object, void
invoke: MutablePropertyReference0.() -> Object    Object
getDelegate: MutablePropertyReference0.() -> Object    Object
isLateinit: PropertyReference.() -> boolean    boolean
isConst: PropertyReference.() -> boolean    boolean
equals: PropertyReference.(Object) -> boolean    Object, boolean
hashCode: PropertyReference.() -> int    int
isSuspend: CallableReference.() -> boolean    boolean
isLateinit: KProperty.() -> boolean    boolean
isConst: KProperty.() -> boolean    boolean
set: KMutableProperty0.(V) -> void    void
getDelegate: KProperty0.() -> Object    Object
equals: AdaptedFunctionReference.(Object) -> boolean    Object, boolean
hashCode: AdaptedFunctionReference.() -> int    int
typeParameter: Reflection.(Object, String, KVariance, boolean) -> KTypeParameter    Object, boolean
setUpperBounds: Reflection.(KTypeParameter, KType) -> void    void
setUpperBounds: Reflection.(KTypeParameter, Array<KType>) -> void    void
invoke: PropertyReference1.(Object) -> Object    Object, Object
getDelegate: PropertyReference1.(Object) -> Object    Object, Object
getDelegate: KProperty1.(T) -> Object    Object
typeOf: ReflectionFactory.(KClassifier, List<KTypeProjection>, boolean) -> KType    boolean
typeParameter: ReflectionFactory.(Object, String, KVariance, boolean) -> KTypeParameter    Object, boolean
setUpperBounds: ReflectionFactory.(KTypeParameter, List<KType>) -> void    void
getArity: FunctionImpl.() -> int    int
invokeVararg: FunctionImpl.(Array<Object>) -> Object    Object
invoke: FunctionImpl.() -> Object    Object
invoke: FunctionImpl.(Object) -> Object    Object, Object
invoke: FunctionImpl.(Object, Object) -> Object    Object, Object, Object
invoke: FunctionImpl.(Object, Object, Object) -> Object    Object, Object, Object, Object
invoke: FunctionImpl.(Object, Object, Object, Object) -> Object    Object, Object, Object, Object, Object
invoke: FunctionImpl.(Object, Object, Object, Object, Object) -> Object    Object, Object, Object, Object, Object, Object
invoke: FunctionImpl.(Object, Object, Object, Object, Object, Object) -> Object    Object, Object, Object, Object, Object, Object, Object
invoke: FunctionImpl.(Object, Object, Object, Object, Object, Object, Object) -> Object    Object, Object, Object, Object, Object, Object, Object, Object
invoke: FunctionImpl.(Object, Object, Object, Object, Object, Object, Object, Object) -> Object    Object, Object, Object, Object, Object, Object, Object, Object, Object
invoke: FunctionImpl.(Object, Object, Object, Object, Object, Object, Object, Object, Object) -> Object    Object, Object, Object, Object, Object, Object, Object, Object, Object, Object
invoke: FunctionImpl.(Object, Object, Object, Object, Object, Object, Object, Object, Object, Object) -> Object    Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object
invoke: FunctionImpl.(Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object) -> Object    Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object
invoke: FunctionImpl.(Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object) -> Object    Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object
invoke: FunctionImpl.(Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object) -> Object    Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object
invoke: FunctionImpl.(Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object) -> Object    Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object
invoke: FunctionImpl.(Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object) -> Object    Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object
invoke: FunctionImpl.(Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object) -> Object    Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object
invoke: FunctionImpl.(Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object) -> Object    Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object
invoke: FunctionImpl.(Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object) -> Object    Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object
invoke: FunctionImpl.(Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object) -> Object    Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object
invoke: FunctionImpl.(Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object) -> Object    Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object
invoke: FunctionImpl.(Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object) -> Object    Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object
invoke: FunctionImpl.(Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object) -> Object    Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object
getArity: FunctionReference.() -> int    int
invoke: MutablePropertyReference1.(Object) -> Object    Object, Object
getDelegate: MutablePropertyReference1.(Object) -> Object    Object, Object
set: KMutableProperty1.(T, V) -> void    void
invoke: PropertyReference0.() -> Object    Object
getDelegate: PropertyReference0.() -> Object    Object
get: MutablePropertyReference1Impl.(Object) -> Object    Object, Object
set: MutablePropertyReference1Impl.(Object, Object) -> void    Object, Object, void
get: MutablePropertyReference2Impl.(Object, Object) -> Object    Object, Object, Object
set: MutablePropertyReference2Impl.(Object, Object, Object) -> void    Object, Object, Object, void
invoke: MutablePropertyReference2.(Object, Object) -> Object    Object, Object, Object
getDelegate: MutablePropertyReference2.(Object, Object) -> Object    Object, Object, Object
set: KMutableProperty2.(D, E, V) -> void    void
getDelegate: KProperty2.(D, E) -> Object    Object
addSpread: SpreadBuilder.(Object) -> void    Object, void
size: SpreadBuilder.() -> int    int
add: SpreadBuilder.(Object) -> void    Object, void
throwCce: TypeIntrinsics.(Object, String) -> void    Object, void
throwCce: TypeIntrinsics.(String) -> void    void
isMutableIterator: TypeIntrinsics.(Object) -> boolean    Object, boolean
asMutableIterator: TypeIntrinsics.(Object) -> Iterator    Object
asMutableIterator: TypeIntrinsics.(Object, String) -> Iterator    Object
castToIterator: TypeIntrinsics.(Object) -> Iterator    Object
isMutableListIterator: TypeIntrinsics.(Object) -> boolean    Object, boolean
asMutableListIterator: TypeIntrinsics.(Object) -> ListIterator    Object
asMutableListIterator: TypeIntrinsics.(Object, String) -> ListIterator    Object
castToListIterator: TypeIntrinsics.(Object) -> ListIterator    Object
isMutableIterable: TypeIntrinsics.(Object) -> boolean    Object, boolean
asMutableIterable: TypeIntrinsics.(Object) -> Iterable    Object
asMutableIterable: TypeIntrinsics.(Object, String) -> Iterable    Object
castToIterable: TypeIntrinsics.(Object) -> Iterable    Object
isMutableCollection: TypeIntrinsics.(Object) -> boolean    Object, boolean
asMutableCollection: TypeIntrinsics.(Object) -> Collection    Object
asMutableCollection: TypeIntrinsics.(Object, String) -> Collection    Object
castToCollection: TypeIntrinsics.(Object) -> Collection    Object
isMutableList: TypeIntrinsics.(Object) -> boolean    Object, boolean
asMutableList: TypeIntrinsics.(Object) -> List    Object
asMutableList: TypeIntrinsics.(Object, String) -> List    Object
castToList: TypeIntrinsics.(Object) -> List    Object
isMutableSet: TypeIntrinsics.(Object) -> boolean    Object, boolean
asMutableSet: TypeIntrinsics.(Object) -> Set    Object
asMutableSet: TypeIntrinsics.(Object, String) -> Set    Object
castToSet: TypeIntrinsics.(Object) -> Set    Object
isMutableMap: TypeIntrinsics.(Object) -> boolean    Object, boolean
asMutableMap: TypeIntrinsics.(Object) -> Map    Object
asMutableMap: TypeIntrinsics.(Object, String) -> Map    Object
castToMap: TypeIntrinsics.(Object) -> Map    Object
isMutableMapEntry: TypeIntrinsics.(Object) -> boolean    Object, boolean
asMutableMapEntry: TypeIntrinsics.(Object) -> Map.Entry    Object
asMutableMapEntry: TypeIntrinsics.(Object, String) -> Map.Entry    Object
castToMapEntry: TypeIntrinsics.(Object) -> Map.Entry    Object
getFunctionArity: TypeIntrinsics.(Object) -> int    Object, int
isFunctionOfArity: TypeIntrinsics.(Object, int) -> boolean    Object, int, boolean
beforeCheckcastToFunctionOfArity: TypeIntrinsics.(Object, int) -> Object    Object, int, Object
beforeCheckcastToFunctionOfArity: TypeIntrinsics.(Object, int, String) -> Object    Object, int, Object
get: PropertyReference2Impl.(Object, Object) -> Object    Object, Object, Object
invoke: PropertyReference2.(Object, Object) -> Object    Object, Object, Object
getDelegate: PropertyReference2.(Object, Object) -> Object    Object, Object, Object
get: PropertyReference1Impl.(Object) -> Object    Object, Object
get: PropertyReference0Impl.() -> Object    Object
stringPlus: Intrinsics.(String, Object) -> String    Object
checkNotNull: Intrinsics.(Object) -> void    Object, void
checkNotNull: Intrinsics.(Object, String) -> void    Object, void
throwNpe: Intrinsics.() -> void    void
throwNpe: Intrinsics.(String) -> void    void
throwJavaNpe: Intrinsics.() -> void    void
throwJavaNpe: Intrinsics.(String) -> void    void
throwUninitializedProperty: Intrinsics.(String) -> void    void
throwUninitializedPropertyAccessException: Intrinsics.(String) -> void    void
throwAssert: Intrinsics.() -> void    void
throwAssert: Intrinsics.(String) -> void    void
throwIllegalArgument: Intrinsics.() -> void    void
throwIllegalArgument: Intrinsics.(String) -> void    void
throwIllegalState: Intrinsics.() -> void    void
throwIllegalState: Intrinsics.(String) -> void    void
checkExpressionValueIsNotNull: Intrinsics.(Object, String) -> void    Object, void
checkNotNullExpressionValue: Intrinsics.(Object, String) -> void    Object, void
checkReturnedValueIsNotNull: Intrinsics.(Object, String, String) -> void    Object, void
checkReturnedValueIsNotNull: Intrinsics.(Object, String) -> void    Object, void
checkFieldIsNotNull: Intrinsics.(Object, String, String) -> void    Object, void
checkFieldIsNotNull: Intrinsics.(Object, String) -> void    Object, void
checkParameterIsNotNull: Intrinsics.(Object, String) -> void    Object, void
checkNotNullParameter: Intrinsics.(Object, String) -> void    Object, void
compare: Intrinsics.(long, long) -> int    long, long, int
compare: Intrinsics.(int, int) -> int    int, int, int
areEqual: Intrinsics.(Object, Object) -> boolean    Object, Object, boolean
areEqual: Intrinsics.(Double, Double) -> boolean    boolean
areEqual: Intrinsics.(Double, double) -> boolean    double, boolean
areEqual: Intrinsics.(double, Double) -> boolean    double, boolean
areEqual: Intrinsics.(Float, Float) -> boolean    boolean
areEqual: Intrinsics.(Float, float) -> boolean    float, boolean
areEqual: Intrinsics.(float, Float) -> boolean    float, boolean
throwUndefinedForReified: Intrinsics.() -> void    void
throwUndefinedForReified: Intrinsics.(String) -> void    void
reifiedOperationMarker: Intrinsics.(int, String) -> void    int, void
reifiedOperationMarker: Intrinsics.(int, String, String) -> void    int, void
needClassReification: Intrinsics.() -> void    void
needClassReification: Intrinsics.(String) -> void    void
checkHasClass: Intrinsics.(String) -> void    void
checkHasClass: Intrinsics.(String, String) -> void    void
anyMagicApiCall: <T> MagicApiIntrinsics.(int) -> T where     int
voidMagicApiCall: MagicApiIntrinsics.(int) -> void    int, void
intMagicApiCall: MagicApiIntrinsics.(int) -> int    int, int
anyMagicApiCall: <T> MagicApiIntrinsics.(Object) -> T where     Object
voidMagicApiCall: MagicApiIntrinsics.(Object) -> void    Object, void
intMagicApiCall: MagicApiIntrinsics.(Object) -> int    Object, int
intMagicApiCall: MagicApiIntrinsics.(int, long, Object) -> int    int, long, Object, int
intMagicApiCall: MagicApiIntrinsics.(int, long, long, Object) -> int    int, long, long, Object, int
intMagicApiCall: MagicApiIntrinsics.(int, Object, Object) -> int    int, Object, Object, int
intMagicApiCall: MagicApiIntrinsics.(int, Object, Object, Object, Object) -> int    int, Object, Object, Object, Object, int
anyMagicApiCall: <T> MagicApiIntrinsics.(int, long, Object) -> T where     int, long, Object
anyMagicApiCall: <T> MagicApiIntrinsics.(int, long, long, Object) -> T where     int, long, long, Object
anyMagicApiCall: <T> MagicApiIntrinsics.(int, Object, Object) -> T where     int, Object, Object
anyMagicApiCall: <T> MagicApiIntrinsics.(int, Object, Object, Object, Object) -> T where     int, Object, Object, Object, Object
mark: InlineMarker.(int) -> void    int, void
mark: InlineMarker.(String) -> void    void
beforeInlineCall: InlineMarker.() -> void    void
afterInlineCall: InlineMarker.() -> void    void
finallyStart: InlineMarker.(int) -> void    int, void
finallyEnd: InlineMarker.(int) -> void    int, void

**Comment by BarkingBad** [comment]
https://kotlinlang.org/docs/reference/java-interop.html#mapped-types
